/**
 * 
 * @author Lucas Martins de Castro <lucas.martins.c03@gmail.com>
 * @since 1.0.0 
 */

/**
 * Request API by EndPoint generated by app
 * @param {EndPoint} endpoint - url search settings
 */
async function getDataAPI (endpoint) {
    let url = endpoint.generateURL();
    const response = await fetch(url)
    const data = await response.json()
    const news = data.articles
    return news;
}

export default getDataAPI;
